---
label: Source:Application
hide_body: true
fields:
- name: name
  type: text
  config:
    required: false
  label: Name
- name: channel
  type: text
  config:
    required: false
  label: Channel
- name: tuning
  type: text
  config:
    required: false
  label: Tuning
