---
label: Source:Security
hide_body: true
fields:
- name: name
  type: text
  config:
    required: false
  label: Name
- name: pollinginterval
  type: number
  label: Polling Interval
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
